
  var students = [
  {
    id: 0,
    name: 'Beth',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    images: "#",
    realImage: "../images/beth.jpg",
    mainImage: "./images/image1alt.jpg",
    moveImage: "../images/cammymove.gif",
  },

  {
    id: 1,
    name: 'Ollie',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    images: "#",
    realImage: "../images/laura.jpg",
    mainImage: "./images/image2.png",
    moveImage: "../images/Dhalsimmove.gif",
  },

  {
    id: 2,
    name: 'David',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    images: "#",
    realImage: "../images/laura.jpg",
    mainImage: "./images/image3.jpg",
    moveImage: "../images/Blankamove.gif",
  },

  {
    id: 3,
    name: 'Dominic',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    images: "#",
    realImage: "../images/laura.jpg",
    mainImage: "./images/image4.png",
    moveImage: "../images/Guilemove.gif",
  },

  {
    id: 4,
    name: 'Nina',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    images: "#",
    realImage: "../images/laura.jpg",
    mainImage: "./images/image5.jpg",
    moveImage: "../images/Chunlimove.gif",
  },

  {
    id: 5,
    name: 'George',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    realImage: "../images/laura.jpg",
    images: "../images/image1.jpg",
    mainImage: "./images/image6.jpg",
    moveImage: "../images/kenmove.gif",
  },

  {
    id: 6,
    name: 'Jacob',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    realImage: "../images/jacob.jpg",
    images: "../images/image1.jpg",
    mainImage: "./images/image7.jpg",
    moveImage: "../images/ryumove.gif",
  },

  {
    id: 7,
    name: 'Ian',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    realImage: "../images/laura.jpg",
    images: "../images/image1.jpg",
    mainImage: "./images/image8.jpg",
    moveImage: "../images/Mbisonmove.gif",
  },

  {
    id: 8,
    name: 'Ife',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    realImage: "../images/laura.jpg",
    images: "../images/image1.jpg",
    mainImage: "./images/image9.jpg",
    moveImage: "../images/Zangiefmove.gif",
  },

  {
    id: 9,
    name: 'Ben Sunderland',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    realImage: "../images/bens.png",
    images: "../images/image1.jpg",
    mainImage: "./images/image10.jpg",
    moveImage: "../images/Balrogmove.gif",
  },

  {
    id: 10,
    name: 'Jody',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    realImage: "../images/laura.jpg",
    images: "../images/image1.jpg",
    mainImage: "./images/image11.jpg",
    moveImage: "../images/sagatmove.gif",
  },

  {
    id: 11,
    name: 'Lulu',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    realImage: "../images/laura.jpg",
    images: "../images/image1.jpg",
    mainImage: "./images/image15.jpg",
    moveImage: "../images/ibukimove.gif",
  },

  {
    id: 12,
    name: 'Laura',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    realImage: "../images/laura.jpg",
    images: "../images/image1.jpg",
    mainImage: "./images/image16.jpg",
    moveImage: "../images/jurimove.gif",
  },

  {
    id: 13,
    name: 'Benjamin Cranwell',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    realImage: "../images/laura.jpg",
    images: "../images/image1.jpg",
    mainImage: "./images/image14.jpg",
    moveImage: "../images/Ehondamove.gif",
  },

  {
    id: 14,
    name: 'General Assembly',
    quote: "here is something quirky",
    description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
    links: "http://www.sirrahmj.co.uk/WDI_Directory/",
    mainImage: "./images/galogo.png",
  },
  ];

  var instructors = [
    {
      id: 0,
      name: 'Gerry',
      quote: "here is something quirky",
      description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
      links: "http://www.sirrahmj.co.uk/WDI_Directory/",
      realImage: "../images/laura.jpg",
      images: "#",
      mainImage: "./images/instructorA.jpg",
      moveImage: "../images/instructormoveraid.GIF",
    },

    {
      id: 1,
      name: 'Mathilda',
      quote: "here is something quirky",
      description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
      links: "http://www.sirrahmj.co.uk/WDI_Directory/",
      realImage: "../images/laura.jpg",
      images: "#",
      mainImage: "./images/instructorC.jpg",
      moveImage: "../images/instructormovesony.gif",
    }, 

    {
      id: 2,
      name: 'Tobias',
      quote: "here is something quirky",
      description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
      links: "http://www.sirrahmj.co.uk/WDI_Directory/",
      realImage: "../images/laura.jpg",
      images: "#",
      mainImage: "./images/instructorD.jpg",
      moveImage: "../images/instructormovescorp.gif",
    },

    {
      id: 3,
      name: 'Dave',
      quote: "here is something quirky",
      description: "Craft beer art party ugh, typewriter lo\-fi cray fashion axe meditation gentrify small batch biodiesel salvia.  Messenger bag cornhole church\-key Blue Bottle, cold\-pressed kale chips listicle occupy bicycle rights wolf Odd Future +1 sriracha.  Photo booth small batch aesthetic, dreamcatcher selvage locavore DIY paleo vinyl gentrify 8\-bit.  Cardigan PBR skateboard disrupt typewriter.  Cardigan scenester hella, Helvetica normcore readymade tattooed pop\-up.  Photo booth food truck Godard, salvia before they sold out small batch fixie ennui dreamcatcher Cosby sweater.  Chambray pug chillwave coldpressed, trust fund seitan Echo Park." ,
      links: "http://www.sirrahmj.co.uk/WDI_Directory/",
      realImage: "../images/laura.jpg",
      images: "#",
      mainImage: "./images/instructorB.jpg",
      moveImage: "../images/instructormovesubz.GIF",
    },
  ];